Added timer form component and small refactor
codeep/timer-app pull request #3
Opened 2021-05-21 08:46 UTC by ReeK15

2021-05-21 09:43 UTC, vlad-grigoryan requested changes

2021-05-21 09:43 UTC, vlad-grigoryan commented on src/app/form/form.component.html
> +    <modal [ngClass] = "{'hhidden': isHidden, 'sshow': !isHidden}" id="modal_1" class="hhidden">
please delete unused ngClass

2021-05-24 06:35 UTC, DavoII requested changes

2021-05-24 06:35 UTC, DavoII commented on src/app/wrapper/wrapper.component.ts
> +  timerForm(event: any): void {
Give  event the correct type

2021-05-24 06:35 UTC, DavoII commented on src/app/wrapper/wrapper.component.ts
> +    const { count } = event;
```js
const { name, description, comment, count  } = event;
```

2021-05-24 09:07 UTC, DavoII approved these changes

2021-05-24 09:09 UTC, vlad-grigoryan approved these changes

2021-05-24 09:09 UTC, merged